import {exportJPEG, getSvg} from "../util/util.js";


export async function router(req, res) {
    try {
        const data = req.fields || {};
        const svg = await panel_M2(data);
        res.set('Content-Type', 'image/jpeg');
        res.send(await exportJPEG(svg));
    } catch (e) {
        console.error(e);
        res.status(500).send(e.stack);
    }
    res.end();
}

export async function router_svg(req, res) {
    try {
        const data = req.fields || {};
        const svg = await panel_M2(data);
        res.set('Content-Type', 'image/svg+xml'); //svg+xml
        res.send(Buffer.from(svg));
    } catch (e) {
        console.error(e);
        res.status(500).send(e.stack);
    }
    res.end();
}

/**
 * 麻婆信息面板 v2, 展示麻婆谱面的
 * !im xxx
 * @param data
 * @return {Promise<string>}
 */
export async function panel_M2(data = {
    user: {},
    most_popular_beatmap: [{
        anime_cover: true,
        artist: 'Wang Rui',
        artist_unicode: '汪睿',
        availability: [Object],
        beatmaps: [Array],
        bpm: 162,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 503,
        genre_id: 5,
        has_leader_board: true,
        id: 1087774,
        is_scoreable: true,
        language_id: 4,
        last_updated: '2022-03-05T07:06:50+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1005413',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 272162,
        preview_name: 'Wang Rui - Tao Hua Xiao (Muziyami)',
        preview_url: '//b.ppy.sh/preview/1087774.mp3',
        ranked: 1,
        ranked_date: '2022-03-13T17:42:04+08:00',
        rating: 9.4598,
        ratings: [Array],
        related_tags: [],
        source: '小女花不弃',
        spotlight: false,
        status: 'ranked',
        storyboard: true,
        submitted_date: '2020-01-02T14:41:13+08:00',
        tags: 'peach blossom cpop c-pop pop chinese 古风 oriental bilibili cover rearrangement 纳兰寻风 na lan xun feng 西门振 xi men zhen 青萝子 qing luo zi op opening xiao nv hua bu qi i will never let you go houshou hari dacaigou kisaki dahkjdas -ovo-',
        title: 'Tao Hua Xiao',
        title_unicode: '桃花笑',
        user_id: 7003013,
        video: false
    }, {
        anime_cover: true,
        artist: 'ginkiha',
        artist_unicode: 'ginkiha',
        availability: [Object],
        beatmaps: [Array],
        bpm: 175,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 276,
        genre_id: 10,
        has_leader_board: true,
        id: 1789653,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2022-10-15T12:39:34+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1597442',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 218230,
        preview_name: 'ginkiha - Ixia Polystachya (Sentou) (Muziyami)',
        preview_url: '//b.ppy.sh/preview/1789653.mp3',
        ranked: 1,
        ranked_date: '2022-10-22T16:02:46+08:00',
        rating: 9.56743,
        ratings: [Array],
        related_tags: [],
        source: 'Alice In Cradle',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2022-06-20T04:29:23+08:00',
        tags: "アリス イン クレイドル アリクレ arikure 愛麗絲搖籃 摇篮里的爱丽丝 cool_03 moe kotonami kotoki_1_3_3_7 kotoki1337 binfhone [paw]ochikouri aurorae dahkjdas ひなゆあ hinayua 橋野みずは hashino mizuha 依克西娅 波利斯塔基亚 伊夏 波利斯塔切尔 伊庫夏 波利斯塔奇亞 ixia_battle 战斗 noel cornehl 诺艾尔 诺艾儿 柯涅尔 諾艾爾 柯奈爾 original soundtrack ost bgm background music mole's nest snake 土龙巢穴 土竜の巣 土蛇 video game ryona リョナ pixel arpg act action roll playing dnb drum & bass n and japanese electronic future instrumental complextro",
        title: 'Ixia Polystachya (Sentou)',
        title_unicode: 'イクシャ・ポリスタキア（戦闘）',
        user_id: 7003013,
        video: false
    }, {
        anime_cover: false,
        artist: 'Azuelle',
        artist_unicode: 'Azuelle',
        availability: [Object],
        beatmaps: [Array],
        bpm: 195,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 287,
        genre_id: 10,
        has_leader_board: true,
        id: 1433130,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2022-01-22T16:28:12+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1298703',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 154931,
        preview_name: 'Azuelle - iced soda (Muziyami)',
        preview_url: '//b.ppy.sh/preview/1433130.mp3',
        ranked: 1,
        ranked_date: '2022-02-03T08:04:09+08:00',
        rating: 9.22222,
        ratings: [Array],
        related_tags: [],
        source: '',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2021-04-15T14:08:16+08:00',
        tags: 'tjkfred kawaii future bass electronic instrumental edm dance chinese',
        title: 'iced soda',
        title_unicode: 'iced soda',
        user_id: 7003013,
        video: false
    }, {
        anime_cover: true,
        artist: 'HOYO-MiX',
        artist_unicode: 'HOYO-MiX',
        availability: [Object],
        beatmaps: [Array],
        bpm: 168,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 534,
        genre_id: 2,
        has_leader_board: true,
        id: 1884753,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2023-07-11T15:44:20+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1675223',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 126690,
        preview_name: 'HOYO-MiX - Surasthana Fantasia (Muziyami)',
        preview_url: '//b.ppy.sh/preview/1884753.mp3',
        ranked: 1,
        ranked_date: '2023-07-19T19:03:10+08:00',
        rating: 9.05046,
        ratings: [Array],
        related_tags: [],
        source: '原神',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2022-11-13T14:52:11+08:00',
        tags: 'genshin impact yuanshen jing shan de xia ge スラサタンナ幻想曲 boundless bliss nahida na xi da 纳西妲 ナヒーダ 小吉祥草王 クラクサナリデビ クサナリ lesser lord kusanali 布耶尔 buer 白草净华 physic of purity 无垠无忧 無垠無憂 mugen muyuu vgm trailer spoiler 所聞遍計 所闻遍计 한계도 걱정도 없이 나히다 hua ling 花玲 tamura yukari 田村ゆかり 须弥 sumeru スメール ost chinese original sound track soundtrack video game videogame instrumental electronic future bass theme @hoyo-mix 草神 dendro archon sfuture艺术团 sfutureart yu-peng chen 陈宇鹏 陈致逸 yijun jiang 姜以君 the stellar moments vol. 3 album 闪耀的群星3 輝く星々vol.3 volume three patchouli-r kobayakawa sae hngjss [charlie lam] skystar chorus character demo aranara 兰那罗 アランナラ 米哈游 mihoyo hoyoverse',
        title: 'Surasthana Fantasia',
        title_unicode: '净善的遐歌',
        user_id: 7003013,
        video: true
    }, {
        anime_cover: true,
        artist: 'Dark PHOENiX',
        artist_unicode: 'Dark PHOENiX',
        availability: [Object],
        beatmaps: [Array],
        bpm: 144,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 161,
        genre_id: 2,
        has_leader_board: true,
        id: 2022219,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2024-02-08T15:42:57+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1789565',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 98508,
        preview_name: 'Dark PHOENiX - Yuuga ni Sakase, Sumizome no Sakura (Muziyami)',
        preview_url: '//b.ppy.sh/preview/2022219.mp3',
        ranked: 1,
        ranked_date: '2024-02-15T16:42:59+08:00',
        rating: 9.62371,
        ratings: [Array],
        related_tags: [],
        source: '東方妖々夢　～ Perfect Cherry Blossom.',
        spotlight: false,
        status: 'ranked',
        storyboard: true,
        submitted_date: '2023-07-07T12:31:36+08:00',
        tags: '東方project th07 優雅に咲かせ、墨染の桜 ～ border of life touhou zun 西行寺 幽々子 幽幽子 saigyouji yuyuko __ag bloom nobly cherry blossoms sumizome video game metal arrow realize c77 comic market 2009 instrumental arrangement 稲井ゆう inai yuu yu- 玉井祐也 yuya tamai utopialyric 姫川紫音 himekawa shion yhc hidden cup season 3 s3 tiebreaker tb',
        title: 'Yuuga ni Sakase, Sumizome no Sakura',
        title_unicode: '幽雅に咲かせ、墨染の桜',
        user_id: 7003013,
        video: false
    }, {
        anime_cover: true,
        artist: 'HOYO-MiX',
        artist_unicode: 'HOYO-MiX',
        availability: [Object],
        beatmaps: [Array],
        bpm: 108,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 101,
        genre_id: 2,
        has_leader_board: true,
        id: 1934236,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2024-03-03T18:42:31+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1716445',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 52656,
        preview_name: 'HOYO-MiX - Immaculate Ardency (Muziyami)',
        preview_url: '//b.ppy.sh/preview/1934236.mp3',
        ranked: 1,
        ranked_date: '2024-03-11T15:22:28+08:00',
        rating: 8.09565,
        ratings: [Array],
        related_tags: [],
        source: '原神',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2023-02-03T16:11:06+08:00',
        tags: 'genshin impact yuanshen qiong hua ying rui 瑶瑶 瑤瑤 yaoyao ヨォーヨ 요요 仙桂莹澈 仙桂瑩澈 仙桂清澄 sweet clouds 樨馨云外飘 purity of the blossoming osmanthus 순수한 선인의 계화꽃 月桂 yuegui 월계 璃月 liyue リーユェ 리월 chinese 原声带 ost original sound track soundtrack video game videogame instrumental folk electronic 主题曲 theme テーマ yijun jiang 姜以君 the stellar moments vol. 4 album 闪耀的群星4 輝く星々vol.4 volume four chuuwon yamakudzi zhongchujiguang -claris- yorita yoshino character demo 米哈游 mihoyo hoyoverse',
        title: 'Immaculate Ardency',
        title_unicode: '琼花映蕊',
        user_id: 7003013,
        video: true
    }],
    genre: [232, 85, 17, 35, 106, 5, 13, 1, 102, 7, 3, 40, 1],
    language: [222, 9, 111, 113, 101, 1, 0, 0, 0, 0, 0, 0, 0, 5],
    difficulty_arr: [90, 80, 125, 115, 56, 10, 1, 2],
    length_arr: [58, 115, 116, 49, 74, 42, 18, 7],
    recent_activity: [{
        approval: 'ranked',
        beatmapset: [Object],
        created_at: '2026-06-01T14:47:43Z',
        id: 1020995053,
        is_mapping: true,
        type: 'BeatmapsetApprove',
        user: [Object]
    }, {
        beatmapset: [Object],
        created_at: '2026-05-25T08:01:29Z',
        id: 1018343518,
        is_mapping: true,
        type: 'BeatmapsetUpdate',
        user: [Object]
    }],
    most_recent_ranked_beatmap: [{
        anime_cover: false,
        artist: 'MC MONG',
        artist_unicode: 'MC몽',
        availability: [Object],
        beatmaps: [Array],
        bpm: 122,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 26,
        genre_id: 5,
        has_leader_board: true,
        id: 2490202,
        is_scoreable: true,
        language_id: 6,
        last_updated: '2026-05-25T08:01:28+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/2204922',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [],
        play_count: 2578,
        preview_name: 'MC MONG - Sick Enough to Die (feat. Mellow) (Muziyami)',
        preview_url: '//b.ppy.sh/preview/2490202.mp3',
        ranked: 1,
        ranked_date: '2026-06-01T14:47:43+08:00',
        rating: 8.66667,
        ratings: [Array],
        related_tags: [],
        source: '',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2026-01-08T23:06:52+08:00',
        tags: 'siyuyuko blue brand 2nd trauma part 2 박장근 김건우 송기홍 korean pop kpop k-pop qq speed qq飞车 english mc夢 mc梦 신동현 shin donghyun hiphop hip hop electronic 节奏大 师 rhythm master 死一样的痛过',
        title: 'Sick Enough to Die (feat. Mellow)',
        title_unicode: '죽을 만큼 아파서 (feat. 멜로우)',
        user_id: 7003013,
        video: false
    }, {
        anime_cover: true,
        artist: 'Fei Zao Jun',
        artist_unicode: '肥皂菌',
        availability: [Object],
        beatmaps: [Array],
        bpm: 175,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Muziyami',
        discussion_locked: false,
        favourite_count: 80,
        genre_id: 4,
        has_leader_board: true,
        id: 1840959,
        is_scoreable: true,
        language_id: 3,
        last_updated: '2025-07-08T16:33:01+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/1639387',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 50256,
        preview_name: 'Fei Zao Jun - Ying Zhi Gui Ji (Muziyami)',
        preview_url: '//b.ppy.sh/preview/1840959.mp3',
        ranked: 1,
        ranked_date: '2025-07-16T16:04:47+08:00',
        rating: 9.12727,
        ratings: [Array],
        related_tags: [],
        source: '',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2022-09-02T10:35:17+08:00',
        tags: '鷹のキセキ 鷹の軌跡 taka no kiseki hatsune miku 初音ミク vocaloid 珉珉的猫咪 凌音音乐ascentone windbell burning gyro one ocean 狼 lang chair88 daremo original traditional folk uplifting 燃 asian japanese 和風 和风 warock j-rock rock pop chinese 2016 dahkjdas [paw]ochikouri binfhone',
        title: 'Ying Zhi Gui Ji',
        title_unicode: '鹰之轨迹',
        user_id: 7003013,
        video: true
    }],
    most_recent_ranked_guest_diff: [{
        anime_cover: false,
        artist: 'Xeami',
        artist_unicode: '世阿弥',
        availability: [Object],
        beatmaps: [Array],
        bpm: 208,
        can_be_hyped: false,
        covers: [Object],
        creator: '09kami',
        discussion_locked: false,
        favourite_count: 33,
        genre_id: 6,
        has_leader_board: true,
        id: 2444103,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2026-05-11T05:16:03+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/2136492',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 9688,
        preview_name: 'Xeami - Ryougen no Mai (09kami)',
        preview_url: '//b.ppy.sh/preview/2444103.mp3',
        ranked: 1,
        ranked_date: '2026-05-23T01:44:34+08:00',
        rating: 9.21429,
        ratings: [Array],
        related_tags: [],
        source: '太鼓の達人',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2025-10-03T11:06:20+08:00',
        tags: 'smallboat minakami yuki koiyuki flower pw384 regraz mafumafu muziyami _lai 太鼓の达人12 ド～ン！と増量版 清水达也 tatsh りょうげんのまい ryogen ナムコオリジナル cyanocitcho cryacho namco original video game music japanese instrumental zeami taiko no tatsujin [hatsune miku] sorairokarasu iroseka inazuma 384059043 electronic folk',
        title: 'Ryougen no Mai',
        title_unicode: '燎原ノ舞',
        user_id: 443031,
        video: false
    }, {
        anime_cover: false,
        artist: 'Kiryu',
        artist_unicode: '桐生',
        availability: [Object],
        beatmaps: [Array],
        bpm: 184,
        can_be_hyped: false,
        covers: [Object],
        creator: 'Flower',
        discussion_locked: false,
        favourite_count: 57,
        genre_id: 10,
        has_leader_board: true,
        id: 213434,
        is_scoreable: true,
        language_id: 5,
        last_updated: '2026-04-22T13:42:11+08:00',
        legacy_thread_url: 'https://osu.ppy.sh/community/forums/topics/243434',
        mappers: [],
        nominations_summary: [Object],
        nominators: [],
        nsfw: false,
        offset: 0,
        pack_tags: [Array],
        play_count: 27192,
        preview_name: 'Kiryu - EVE (Flower)',
        preview_url: '//b.ppy.sh/preview/213434.mp3',
        ranked: 1,
        ranked_date: '2026-04-29T17:22:59+08:00',
        rating: 9.07692,
        ratings: [Array],
        related_tags: [],
        source: '',
        spotlight: false,
        status: 'ranked',
        storyboard: false,
        submitted_date: '2014-09-15T21:38:18+08:00',
        tags: 'niconico indies nni drum and bass dnb instrumental electronic dahkjdas z1085684963 muziyami',
        title: 'EVE',
        title_unicode: 'EVE',
        user_id: 1033017,
        video: false
    }],
    favorite: 2380,
    playcount: 2340576,
    guest_differs: [{
        user: [Object], received: 1, received_ranked: 0, sent: 5, sent_ranked: 5
    }, {
        user: [Object], received: 6, received_ranked: 5, sent: 0, sent_ranked: 0
    }, {
        user: [Object], received: 1, received_ranked: 0, sent: 5, sent_ranked: 5
    }, {
        user: [Object], received: 0, received_ranked: 0, sent: 5, sent_ranked: 5
    }, {
        user: [Object], received: 4, received_ranked: 4, sent: 4, sent_ranked: 0
    }, {
        user: [Object], received: 0, received_ranked: 0, sent: 5, sent_ranked: 4
    }, {
        user: [Object], received: 0, received_ranked: 0, sent: 4, sent_ranked: 3
    }],
    total_gds: 87,
    total_diffs: 479
}) {
    console.log(data)


    return getSvg('<g></g>')
}