name: update image
on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Fast local pull
        run: |
          git fetch origin master --depth=1
          git reset --hard origin/master

      - name: Update or Install
        run: |
          set -e
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MSG"
          
          if echo "$COMMIT_MSG" | grep -qiE "\[npm\]|\[install\]|\[i\]"; then
            ~/sh/install_node_object.sh
          else
            ~/sh/update_node_object.sh
          fi